language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
- cd dynamic_commands/tests
# command to run tests
script:
  - pytest test.py